apiVersion: v1
kind: Pod
metadata:
    name: client
    namespace: hadoop
    labels:
      app: client
spec:
  nodeSelector:
    hadoop-client: "true"
  containers:
    - name: client
      image: ghcr.io/liusheng/hadoop-client
      imagePullPolicy: Always
      env:
        - name: HADOOP_CONTROLLER
          value: controller
  restartPolicy: Always
